language: cpp

sudo: required

before_script:
  - mkdir build
  - cd build
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
  - cmake ..
script:
  - gcc --version
  - make
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
