/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_nntu_aes_AesJavaWrapper */

#ifndef _Included_com_nntu_aes_AesJavaWrapper
#define _Included_com_nntu_aes_AesJavaWrapper

#include <jdwpTransport.h>
#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nntu_aes_AesJavaWrapper
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nntu_aes_AesJavaWrapper_encrypt(JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_nntu_aes_AesJavaWrapper
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nntu_aes_AesJavaWrapper_decrypt(JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_nntu_aes_AesJavaWrapper
 * Method:    padWithZeros
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nntu_aes_AesJavaWrapper_padWithZeros(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
